"""empty message

Revision ID: e002b7f702dc
Revises: 
Create Date: 2022-03-03 17:21:05.966576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e002b7f702dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogposts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('tag', sa.String(length=120), nullable=True),
    sa.Column('cover', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blogposts_content'), 'blogposts', ['content'], unique=True)
    op.create_index(op.f('ix_blogposts_cover'), 'blogposts', ['cover'], unique=True)
    op.create_index(op.f('ix_blogposts_date'), 'blogposts', ['date'], unique=True)
    op.create_index(op.f('ix_blogposts_tag'), 'blogposts', ['tag'], unique=True)
    op.create_index(op.f('ix_blogposts_title'), 'blogposts', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blogposts_title'), table_name='blogposts')
    op.drop_index(op.f('ix_blogposts_tag'), table_name='blogposts')
    op.drop_index(op.f('ix_blogposts_date'), table_name='blogposts')
    op.drop_index(op.f('ix_blogposts_cover'), table_name='blogposts')
    op.drop_index(op.f('ix_blogposts_content'), table_name='blogposts')
    op.drop_table('blogposts')
    # ### end Alembic commands ###
