"""empty message

Revision ID: 9671cffc53aa
Revises: 2ecb73aefab4
Create Date: 2022-03-04 23:59:36.297705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9671cffc53aa'
down_revision = '2ecb73aefab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'companies', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'user_id')
    # ### end Alembic commands ###
