"""empty message

Revision ID: aceb60e0e93a
Revises: 6be663ad8f5c
Create Date: 2022-03-04 23:18:31.131870

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "aceb60e0e93a"
down_revision = "6be663ad8f5c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kamal",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("registered_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kamal")
    # ### end Alembic commands ###
