"""empty message

Revision ID: c0c0a52d94e0
Revises: aceb60e0e93a
Create Date: 2022-03-04 23:46:52.102761

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c0c0a52d94e0"
down_revision = "aceb60e0e93a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kamal")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kamal",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "registered_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="kamal_pkey"),
        sa.UniqueConstraint("email", name="kamal_email_key"),
    )
    # ### end Alembic commands ###
